export const STAGES = ['cutting', 'assembly', 'erection', 'outfitting'] as const

export const config = {
  TIME: {
    weeksPerRun: 48,
    startWeek: 1,
  },

  TRIGGERS: {
    fatigueBadge: 70,
    fatigueWalkoff: 85,
    walkoffChance: 0.1,
    walkoffWeeks: 2,
    cashWarning: 0,
    cashWarningDeep: -150000,
    cashBankrupt: -250000,
    deadlineUrgentWeeks: 3,
    projectionHorizon: 80,
  },

  YARD: {
    m0Berths: 1,
    m1Berths: 1,
    maxBerths: 4,
    gantryServeDistance: 4,
    gantryBonusDistance: 2,
    gantryBonus: 0.15,
    erectionSlots: { small: 2, medium: 3, large: 4 },
  },

  FACILITIES: {
    buildWeeks: 3,
    relocateWeeks: 2,
    relocateCost: 0.6,
    demolishWeeks: 1,
    demolishRefund: 0.4,
    catalog: {
      smallBerth: {
        name: 'Small Berth',
        cost: 180000,
        upkeep: 6000,
        weeks: 3,
        size: 'small' as const,
        footprint: [2, 2] as const,
      },
      mediumBerth: {
        name: 'Medium Berth',
        cost: 420000,
        upkeep: 12000,
        weeks: 3,
        size: 'medium' as const,
        footprint: [3, 2] as const,
      },
      largeBerth: {
        name: 'Large Berth',
        cost: 900000,
        upkeep: 22000,
        weeks: 3,
        size: 'large' as const,
        footprint: [4, 3] as const,
      },
      plateShop: {
        name: 'Plate Shop',
        cost: 150000,
        upkeep: 8000,
        weeks: 3,
        footprint: [2, 2] as const,
        slots: 2,
      },
      assemblyBay: {
        name: 'Assembly Bay',
        cost: 260000,
        upkeep: 11000,
        weeks: 3,
        footprint: [3, 2] as const,
        slots: 3,
      },
      gantryCrane: {
        name: 'Gantry Crane',
        cost: 340000,
        upkeep: 9000,
        weeks: 3,
        footprint: [2, 1] as const,
      },
      outfitQuay: {
        name: 'Outfit Quay',
        cost: 200000,
        upkeep: 7000,
        weeks: 3,
        footprint: [2, 2] as const,
        slots: 2,
      },
      storageYard: {
        name: 'Storage Yard',
        cost: 90000,
        upkeep: 3000,
        weeks: 3,
        footprint: [2, 2] as const,
        storageTons: 400,
      },
    },
  },

  SHIPS: {
    coastalFreighter: {
      id: 'coastalFreighter' as const,
      name: 'Coastal Freighter',
      size: 'small' as const,
      workUnits: 400,
      typicalWeeks: 10,
      stageShare: { cutting: 0.2, assembly: 0.35, erection: 0.3, outfitting: 0.15 },
      stageWork: { cutting: 80, assembly: 140, erection: 120, outfitting: 60 },
      basePayment: 600000,
      steelTons: 120,
      erectionSlots: 2,
    },
    bulkCarrier: {
      id: 'bulkCarrier' as const,
      name: 'Bulk Carrier',
      size: 'medium' as const,
      workUnits: 900,
      typicalWeeks: 16,
      stageShare: { cutting: 0.2, assembly: 0.35, erection: 0.3, outfitting: 0.15 },
      stageWork: { cutting: 180, assembly: 315, erection: 270, outfitting: 135 },
      basePayment: 1600000,
      steelTons: 320,
      erectionSlots: 3,
    },
    productTanker: {
      id: 'productTanker' as const,
      name: 'Tanker',
      size: 'large' as const,
      workUnits: 1600,
      typicalWeeks: 24,
      stageShare: { cutting: 0.2, assembly: 0.35, erection: 0.3, outfitting: 0.15 },
      stageWork: { cutting: 320, assembly: 560, erection: 480, outfitting: 240 },
      basePayment: 3200000,
      steelTons: 600,
      erectionSlots: 4,
    },
  },

  CREWS: {
    grades: {
      green: { name: 'Green', proficiency: 10, wage: 4000, baseOutput: 20, defectRate: 0.12 },
      certified: { name: 'Certified', proficiency: 25, wage: 9000, baseOutput: 45, defectRate: 0.04 },
      master: { name: 'Master', proficiency: 40, wage: 16000, baseOutput: 70, defectRate: 0.015 },
    },
    inheritedCertifiedAssembly: 55,
    m0StartingCrews: [
      { id: 'alden', name: 'Alden' },
      { id: 'briggs', name: 'Briggs' },
      { id: 'cho', name: 'Cho' },
      { id: 'dunn', name: 'Dunn' },
    ],
    m0Grade: 'green' as const,
  },

  PROFICIENCY: {
    producingGain: 6,
    otherDecay: 2,
    min: 0,
    max: 100,
    multBase: 0.7,
    multPerPoint: 0.006,
    green: 10,
    certified: 25,
    master: 40,
  },

  FATIGUE: {
    producing: 4,
    rush: 18,
    rest: -12,
    overflow: 0,
    min: 0,
    max: 100,
    penaltyStart: 50,
    penaltyDivisor: 125,
  },

  QUALITY: {
    grades: ['excellent', 'good', 'questionable', 'concerning'] as const,
    start: 'good' as const,
    inheritedBulkCarrierLocked: 'good' as const,
    inheritedBulkCarrierAccruesDefects: false,
    defectQualityHit: 8,
    seaTrialReworkCost: 60000,
    seaTrialReworkWeeks: 3,
    settleCost: 110000,
    settleRepHit: 3,
    admiraltyMult: 2,
    gauge: {
      excellent: { min: 0, max: 0 },
      good: { min: 1, max: 2 },
      questionable: { min: 3, max: 5 },
      concerning: { min: 6, max: 999 },
    },
  },

  REPUTATION: {
    start: 50,
    min: 0,
    max: 100,
    abandonNotStarted: -15,
    abandonInProgress: -8,
    onTimeDelivery: 2,
    earlyDelivery: 3,
    lateDelivery: -3,
    bankrupt: -25,
  },

  STEEL: {
    startPrice: 1100,
    minPrice: 700,
    maxPrice: 1900,
    weeklyDrift: 0.08,
    freighterTons: 120,
    bulkTons: 320,
    tankerTons: 600,
  },

  ECONOMY: {
    m0StartCash: 400000,
    m1StartCash: 500000,
    latePenaltyPerWeek: 40000,
    advancePercent: 0.3,
    deliveryPercent: 0.7,
    earlyBonusPerWeek: 0.03,
    rushWagePremium: 0.6,
    rushOutputMult: 1.4,
    mortgagePrincipal: 12500,
    mortgageInterest: 5500,
    mortgageRemainingStart: 600000,
    abandonNotStartedRefund: 1.0,
    abandonInProgressRefund: 0,
    wildcatWageForever: 0.15,
    wildcatIdleWeeks: 2,
  },

  CONTRACTS: {
    offerSlots: 3,
    maxAge: 3,
    paymentMin: 0.92,
    paymentMax: 1.12,
    deadlineBase: 10,
    deadlineMin: 0.8,
    deadlineMax: 1.25,
    rushChance: 0.2,
    rushDeadlineMult: 0.75,
    rushPaymentMult: 1.3,
    minDeadlineWeeks: 1,
  },

  SCORING: {
    cashWeight: 1,
    facilityBuildCostWeight: 0.5,
    reputationWeight: 20000,
    remainingMortgageWeight: 1,
    earlyEndWeekPenalty: 40000,
    bankruptScore: 0,
  },

  LEDGER: {
    fatigueUnit: 'raw',
    shadowCash: false,
    wageLine: true,
    penaltyLine: true,
    deliveryLine: true,
  },

  SHARING: {
    dailySeedPrefix: 'daily',
    ghostRuns: false,
    replayCompatible: true,
  },

  M0: {
    defaultSeed: 'drydock-m0',
    inheritedHull: {
      id: 'hull-1',
      name: 'Hull 1',
      classId: 'coastalFreighter' as const,
      stage: 'assembly' as const,
      workInStage: 40,
      totalWorkDone: 120,
      deadlineWeek: 8,
      payment: 600000,
      rush: false,
      acceptedWeek: 1,
    },
  },
} as const

export type ShipClassId = keyof typeof config.SHIPS
export type CrewGrade = keyof typeof config.CREWS.grades
